### ISSUE TITLE
Jellyfin not finding some studios images

### ISSUE THREAD

**Issue by Daivy03** [Entree3k/Jellyfin#11]
### I checked that they exist in this repo but jellyfin cannot find the following studios:

1. paramount+
2. disney+
3. abc tv
4. antena 3

The only ones that jellyfin found are:

1. netflix
2. hbo
3. tokyo mx

## Test video
>[!Note]
>Jellyfin Version: 10.8.10
Operating System: Linux
Architecture: Arm64

https://github.com/Entree3k/Jellyfin/assets/75785698/a4775c11-57e1-479a-b02f-7d3a1b29560d

**Comment by Entree3k** [comment]
That is interesting, I am able to pull Disney+. I'll have to look into this and see what could be the cause.
![image](https://github.com/Entree3k/Jellyfin/assets/28127566/c1b50680-c830-4acf-88e6-89488610242c)
