### ISSUE TITLE
Your raw github is down

### ISSUE THREAD

**Issue by DevilsDesigns** [Entree3k/Jellyfin#14]
Your link https://raw.githubusercontent.com/Entree3k/Jellyfin/main/studios

has a 404 error. Please fix

**Comment by Entree3k** [comment]
People constantly say that even the default jellyfin repo has a 404 error that is fine. Did you follow the directions and enter it where it says to or did you just enter that raw url in a browser?

**Comment by DevilsDesigns** [comment]
> People constantly say that even the default jellyfin repo has a 404 error that is fine. Did you follow the directions and enter it where it says to or did you just enter that raw url in a browser? 

I was actually getting an error inside starting of jellyfin for the repo. Giving the same error cannot be reached. I've had the repo running on my jellyfin for about 6 months no issues.

**Comment by Entree3k** [comment]
Oh see that is interesting I was assuming you were just putting it in the browser like many people have done, let me take a look

**Comment by Entree3k** [comment]
And it looks like this?
![image](https://github.com/Entree3k/Jellyfin/assets/28127566/3cc5bc94-847f-411e-8473-902ad2b90886)

It seems to still be working for me 

![image](https://github.com/Entree3k/Jellyfin/assets/28127566/eb4d24d2-baeb-431e-a116-71494f0e4be0)
