### ISSUE TITLE
Add CBC Television 

### ISSUE THREAD

**Issue by SenorSmartyPants** [Entree3k/Jellyfin#7]
Same as CBC I think, but this is how TMDB reports the name. 

https://www.themoviedb.org/network/23?language=en-US

**Comment by SenorSmartyPants** [comment]
Here's some additional networks missing

Showcase https://www.themoviedb.org/network/105
Global TV
https://www.themoviedb.org/network/218

**Comment by Entree3k** [comment]
I added Global TV, Showcase and CBC Television
